name: jogos
channels:
  - conda-forge
dependencies:
  - python
  - dash
  - pandas
  - matplotlib
  - sphinx
  - numpy
  - pip
  - dash-renderer
  - pip:
    - pre-commit
    - dash-bootstrap-components
    - openpyxl